---
name: "Build Archlinux package"
description: "Build Archlinux package"
branding:
  icon: package
  color: blue
inputs:
  repos:
    description: >
         A list of custom repositories.
    required: false
  packages:
    description: >
        A string with a space separated list of aur packages that should
        be built and included in the repository.
    required: true
  scripts:
    required: true
runs:
  using: docker
  image: docker://countstarlight/makepkg:latest
